[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.poetry]
package-mode = true

name = "message_printer"

version = "0.0.3"

description = "Простая библиотека для вывода информационных сообщений "

license = "MIT"

authors = [
    "pydrag0n",
]